<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.natiqhaciyef</groupId>
    <artifactId>alpha-metrics-analytics</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>${project.groupId}:${project.artifactId}</name>
    <description>A high-performance, native-backed analytics tracking engine for Android applications. AlphaMetrics leverages a C++ core via JNI and a spatial ring buffer implementation to deliver low-latency, thread-safe event logging with minimal CPU and memory overhead.</description>
    <url>https://github.com/natiqhaciyef/Alpha-Metrics-Analytics-SDK</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>natiqhaciyef</id>
            <name>Natig Hajiyev</name>
            <email>natiq00h2272@gmail.com</email>
            <organization>AlphaMetrics</organization>
            <organizationUrl>https://github.com/natiqhaciyef</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/natiqhaciyef/Alpha-Metrics-Analytics-SDK.git</connection>
        <developerConnection>scm:git:ssh://github.com:natiqhaciyef/Alpha-Metrics-Analytics-SDK.git</developerConnection>
        <url>https://github.com/natiqhaciyef/Alpha-Metrics-Analytics-SDK/tree/main</url>
    </scm>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>0.7.0</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>${server}</publishingServerId>
                    <autoPublish>true</autoPublish>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.2</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>3.2.7</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>